version: "3.8"

services:
    data:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports: 
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrongPassword12!@
        volumes: 
            - sqldata:/var/opt/mssql 
        networks: 
            - bodysculptor-network
            
    messages:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
            - "5672:5672"
        hostname: "rabbitmq"
        environment:
            - RABBITMQ_ERLANG_COOKIE=Rand0mR4bbitMqCo0k1e
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
        networks: 
            - bodysculptor-network
            
    nutrition:
        container_name: nutrition
        image: krisko95/body-sculptor-nutrition-service
        build:
            context: ./src/Server
            dockerfile: ./BodySculptor.Nutrition/Dockerfile
        ports: 
            - "5006:80"
        env_file: ./src/Server/BodySculptor.Common/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BodyScultporNutritionDb;User Id=sa;Password=yourStrongPassword12!@;MultipleActiveResultSets=true

        restart: on-failure
        volumes:
            - ./.aspnet/nutrition/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - bodysculptor-network
        depends_on: 
            - data
            
    exercises:
        container_name: exercises
        image: krisko95/body-sculptor-exercises-service
        build:
            context: ./src/Server
            dockerfile: ./BodySculptor.Exercises/Dockerfile
        ports: 
            - "5008:80"
        env_file: ./src/Server/BodySculptor.Common/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BodyScultporExercisesDb;User Id=sa;Password=yourStrongPassword12!@;MultipleActiveResultSets=true

        restart: on-failure
        volumes:
            - ./.aspnet/exercises/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - bodysculptor-network
        depends_on: 
            - data
            
    statistics:
        container_name: statistics
        image: krisko95/body-sculptor-statistics-service
        build:
            context: ./src/Server
            dockerfile: ./BodySculptor.Statistics/Dockerfile
        ports: 
            - "5014:80"
        env_file: ./src/Server/BodySculptor.Common/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BodySculptorStatisticsDb;User Id=sa;Password=yourStrongPassword12!@;MultipleActiveResultSets=true

        restart: on-failure
        volumes:
            - ./.aspnet/statistics/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - bodysculptor-network
        depends_on: 
            - data
            
    articles:
        container_name: articles
        image: krisko95/body-sculptor-articles-service
        build:
            context: ./src/Server
            dockerfile: ./BodySculptor.Articles/Dockerfile
        ports: 
            - "5010:80"
        env_file: ./src/Server/BodySculptor.Common/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BodyScultporArticlesDb;User Id=sa;Password=yourStrongPassword12!@;MultipleActiveResultSets=true

        restart: on-failure
        volumes:
            - ./.aspnet/articles/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - bodysculptor-network
        depends_on: 
            - data
            
    administration:
        container_name: administration
        image: krisko95/body-sculptor-administration-client
        build:
            context: ./src/Server
            dockerfile: ./BodySculptor.Administration/Dockerfile
        ports: 
            - "5012:80"
        env_file: ./src/Server/BodySculptor.Common/Common.env

        restart: on-failure
        volumes:
            - ./.aspnet/administration/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - bodysculptor-network
        depends_on: 
            - data
            
    watchdog:
        container_name: watchdog
        image: krisko95/body-sculptor-watchdog-service
        build:
            context: ./src/Server
            dockerfile: ./BodySculptor.Watchdog/Dockerfile
        ports: 
            - "5016:80"
        env_file: ./src/Server/BodySculptor.Common/Common.env

        restart: on-failure
        volumes:
            - ./.aspnet/watchdog/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - bodysculptor-network
            
    gateway:
        container_name: gateway
        image: krisko95/body-sculptor-gateway-service
        build:
            context: ./src/Server
            dockerfile: ./BodySculptor.Gateway/Dockerfile
        ports: 
            - "5018:80"
        env_file: ./src/Server/BodySculptor.Common/Common.env

        restart: on-failure
        volumes:
            - ./.aspnet/gateway/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - bodysculptor-network
            
    identity:
        container_name: identity
        image: krisko95/body-sculptor-identity-service
        build:
            context: ./src/Server
            dockerfile: ./BodySculptor.Identity/Dockerfile
        ports: 
            - "5003:80"
        env_file: ./src/Server/BodySculptor.Common/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BodySculptorIdentityDb;User Id=sa;Password=yourStrongPassword12!@;MultipleActiveResultSets=true

        restart: on-failure
        volumes:
            - ./.aspnet/identity/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - bodysculptor-network
        depends_on: 
            - data
            - nutrition
            - exercises
            - articles
            
    client:
        container_name: client
        image: krisko95/body-sculptor-user-client
        build:
            context: ./src/Client
            dockerfile: ./Dockerfile
        restart: on-failure
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
        networks: 
            - bodysculptor-network
        depends_on:
            - identity
            - nutrition
            - exercises
            - articles
            - statistics
        stdin_open: true
            
networks:
    bodysculptor-network:

volumes:
    sqldata:
    rabbitmq: