export const IS_AUTHENTICATED = "IS_AUTHENTICATED";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const ON_LOGOUT = "ON_LOGOUT";

export const SET_FOODS = "SET_FOODS";
export const START_FETCH_FOODS = "START_FETCH_FOODS";

export const START_FETCH_ARTICLES_STATISTICS = "START_FETCH_ARTICLES_STATISTICS";
export const SET_ARTICLES_STATISTICS = "SET_ARTICLES_STATISTICS";